---
- name: Converge
  hosts: all
  tasks:
    - name: "install crontab"
      ansible.builtin.apt:
        name: "cron"
        state: "present"
        update_cache: "yes"
        cache_valid_time: "3600"
