---
### Run the molecule tests for this package
name: Molecule tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  molecule-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run molecule tests
        run: |
          make test
        env:
          PY_COLORS: 1
          ANSIBLE_FORCE_COLOR: 1
